<?php

$types = array(
	'name'  => 'Name',
	'firstName'  => 'First name',
	'lastName'  => 'Surname',
	'dateNum'  => 'Date',
	'date'  => 'Date ISO',
	'streetAddress' => 'Street',
	'city'  => 'City',
	'postcode'  => 'PSC',
	'phoneNumber' => 'Phone',
	'email' => 'e-mail',
	'login' => 'Login',
	'password' => 'Password',
	'text' => 'Text',
	'constant' => 'Constant'
);

$locales = array(
	'cs_CZ',
	'en_US'
);
